export const twitterDefaultConfig = {
  NUM_TIMELINE_TWEETS: 10,
  NUM_FOLLOWING_RECENT_TWEETS: 10,
  NUM_RANDOM_FOLLOWINGS: 5,
  MAX_MENTIONS: 20,
  MAX_THREAD_LENGTH: 20,
  MAX_MY_RECENT_TWEETS: 10,
  MAX_MY_RECENT_REPLIES: 10,
  RESPONSE_INTERVAL_MS: 60 * 60 * 1000,
  POST_INTERVAL_MS: 90 * 60 * 1000,
  POST_TWEETS: false,
};
