version: '3.8'

services:
  agents:
    build:
      context: .
      dockerfile: agents.Dockerfile
    ports:
      - '${AGENTS_PORT:-3000}:${AGENTS_PORT:-3000}'
    volumes:
      - ./agents:/app
    environment:
      - AGENTS_PORT=${AGENTS_PORT:-3000}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - '${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}'
    volumes:
      - ./backend:/app
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-8000}
      - AGENTS_SERVICE_URL=http://agents:${AGENTS_PORT:-3000}
    depends_on:
      - agents
  
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - '${FRONTEND_PORT:-3001}:${FRONTEND_PORT:-3001}'
    volumes:
      - ./frontend:/app
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-3001}
      - VITE_BACKEND_SERVICE_URL=${BACKEND_SERVICE_URL}
    depends_on:
      - backend