services:
  web-cli:
    image: ghcr.io/autonomys/autonomys-agents/web-cli:${IMAGE_TAG:-latest}
    build:
      context: ../..
      dockerfile: docker/web-cli/Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      PORT: ${PORT:-3000}
      RUNTIME_API_URL: ${RUNTIME_API_URL:-https://localhost:3000}
      RUNTIME_API_TOKEN: ${RUNTIME_API_TOKEN:-}
